#!/usr/bin/env sh

# ╭───────┤ 󱚥 sh41
# │ Entry point for setting up the Shell41 CLI tool into the user's shell.
# │ Source this into your shell rc file, e.g. ~/.bashrc, ~/.zshrc, etc.
# │ 
# │  Do not edit this file directly, instead, use the configuration file 
# │ located at $XDG_CONFIG_HOME/shell41/.sh41rc.
# ╰─

export SH41_HOME="$(dirname "$0")"
export SH41_LIB="$SH41_HOME/lib"
export SH41_BIN="$SH41_HOME/bin"
export PATH="$SH41_BIN:$PATH"

export LOG_NAMESPACE="󱚥 shell41"
export LOG_LEVEL=info

# ╭───────┤  User specific paths
# ╰─

export SH41_LOCAL="$XDG_DATA_HOME/shell41"
export SH41_CACHE="$XDG_CACHE_HOME/shell41"
export SH41_CONFIG_HOME="$XDG_CONFIG_HOME/shell41"
export SH41_CONFIG_RC="$XDG_CONFIG_HOME/shell41/.sh41rc"
export SH41_DB_BACKUPS="$SH41_LOCAL/db_backups"

mkdir -p "$SH41_LOCAL" "$SH41_CACHE" "$SH41_CONFIG_HOME" "$SH41_DB_BACKUPS"

# Change the currently loggin user
sh41_switch () {
  selected_user_id=$(echo "TODO: use 'sh41 users find-many' and 'fzf' to select a user")

  export SH41_USER_ID="$selected_user_id"
}

# ╭───────┤  Load user configuration
# ╰─

if [ -e "$SH41_CONFIG_RC" ]; then
  # shellcheck source=/dev/null
  . "$SH41_CONFIG_RC"
else
  "$SH41_LIB/_scripts/log" error \
    -v config_path "$SH41_CONFIG_RC" \
    -v init_script "sh41 init" \
    "Configuration file not found, please run the init script manually."
fi

