#!/usr/bin/env sh

# NAME
#  exists - Check if a provider exists
#
# SYNOPSIS
#  exists <provider_name>
#
# ENVIRONMENT
#  SH41_LIB
#   Path to SH41 internal lib directory.
#
#  SH41_LIB_PROVIDERS_BACKENDS
#   Path to backends dir, interfaces with the 3rd party LLM providers.
#
#  SH41_ICON
#   SH41 logo icon

# log config
export LOG_NAMESPACE="$SH41_ICON providers/exists"

# shellcheck source=../_fn/trap-debug
. "$SH41_LIB/_fn/trap-debug"

if [ ! -f "$SH41_LIB_PROVIDERS_BACKENDS/$1" ]; then
  log error "Provider $(stylize underline "$1") does not exist"
  exit 1
fi

log success "Provider $(stylize underline "$1") exists"

