#!/usr/bin/env sh

# NAME
#  list - List all available providers
#
# SYNOPSIS
#  providers list
#
# ENVIRONMENT
#  SH41_LIB
#   Path to SH41 internal lib directory.
#
#  SH41_PROVIDERS_BACKENDS
#   Path to backends dir, interfaces with the 3rd party LLM providers.
#
#  SH41_ICON
#   SH41 logo icon

export LOG_NAMESPACE="$LOG_NAMESPACE.send"

# shellcheck source=../_core/fn/trap-debug
. "$SH41_LIB/_core/fn/trap-debug"

find "$SH41_PROVIDERS_BACKENDS" \
  -mindepth 1 -type f -exec basename {} \; \
  | sort
