#!/usr/bin/env sh

# NAME
#  upgrade - Upgrade Shell41 to latest git version.
#
# SYNOPSIS
#  upgrade
#
# ENVIRONMENT
#  SH41_HOME
#   Path to SH41 installation directory.

# ╭───┤ Bootstrap
# ╰─

set -e
export LOG_NAMESPACE="$LOG_NAMESPACE.upgrade"

# shellcheck source=../fn/trap-debug
. "$SH41_LIB/_core/fn/trap-debug"

# ╭───┤ Main 
# ╰─

cd "$SH41_HOME" && {
  if git pull origin master; then 
    log success "Shell41 has been upgraded to the latest version."
  fi
} 
