#!/usr/bin/env sh

# NAME
#  choose - Fancy fzf select box 
#
# SYNOPSIS
#  choose [-p|--prompt <prompt>] [--allow-custom]
#
# STDIN
#  Options to select from, each on a new line.
#
# OPTIONS
#  -p|--prompt <value> 
#   Prompt to display before the options, default: "Select an option:"
#
# FLAGS
#  --allow-custom
#   Allow the user to input a custom text instead or selecting a predefined option.
#
# EXAMPLES
#  find . -type f | choose -p "Select a file:"
#
# SEE ALSO
#  fzf(1), log(1)

# ╭───┤ Bootstrap 
# ╰─

export LOG_NAMESPACE="choose"

# ╭───┤ Parse options
# ╰─

prompt="Select an option:"
allow_custom=""

while [ "$#" -gt 0 ]; do
  case $1 in
    --allow-custom) allow_custom="true" ;;
    -p|--prompt) 
      if [ "$2" ]; then
        prompt="$2"; shift 
      else
        echo "-p|--prompt option requires a value" >&2
        exit 1
      fi
    ;;
    --) shift; break ;;
    -*) log error -v name "$1" "Unknown parameter"; exit 1 ;;
    *) break ;;
  esac
  shift
done

if [ -t 0 ]; then
  log error "No options provided. Options must be passed via stdin."
  exit 1
fi

# ╭───┤ Main
# ╰─

if [ -n "$allow_custom" ]; then
  fzf --reverse --ansi --print-query \
    --height 6 \
    --prompt "$prompt" < /dev/stdin \
    | tr --delete '\n' \
    | head -n 1
else 
  fzf --reverse --ansi \
  --height 6 \
  --prompt "$prompt" < /dev/stdin \
  | tr --delete '\n'
fi

