#!/usr/bin/env sh

# NAME
#  choose 
#
# SYNOPSIS
#  choose [-p|--prompt <prompt>]
#
# DESCRIPTION
#  Wrapper script for rofi or fzf to select an option from stdin.
#  If DISPLAY is set, rofi is used, otherwise fzf is used.
#
# OPTIONS
#  -p|--prompt <value> 
#   Prompt to display before the options, default: "Select an option:"
#
# EXAMPLES
#  find . -type f | choose -p "Select a file:"
#
# SEE ALSO
#  fzf(1)

PROMPT="Select an option:"

while [ "$#" -gt 0 ]; do
  case $1 in
    -p|--prompt) PROMPT="$2"; shift ;;
    *) echo "Unknown parameter: $1"; exit 1 ;;
  esac
  shift
done

if [ -t 0 ]; then
  echo "No options provided. Options must be passed via stdin." >&2
  exit 1
fi

cat \
  | fzf --reverse --ansi --height 6 --prompt "$PROMPT" --print-query
