#!/usr/bin/env sh

# NAME
#  trace-process - Print the hierarchy of processes that led to the current
#  process 
# 
# SYNOPSIS
#  trace-process
#
# ENVIRONMENT
#  SH41_ROOT_PID
#   The root process id. Used to know when to stop the stack trace.
#
#  SH41_HOME
#   The path to the SH41 home directory.

# Skipping our own process since it's not relevant
current_pid="$PPID"
stop_pid="${SH41_ROOT_PID:-1}"

if [ -z "$CI" ]; then
  printf "\033[90m"
fi

echo "Process stack trace:"
while [ "$current_pid" -ge "$stop_pid" ]; do 
  read -r current_pid parent_pid args <<-EOF
$(ps -o pid=,ppid=,args= -p "$current_pid")
EOF

  # Trim out SH41_HOME for easier reading
  echo " [$current_pid]: $args" | sed "s|$SH41_HOME/|\$SH41_HOME/|"

  current_pid=$parent_pid
done

if [ -z "$CI" ]; then
  printf "\033[0m"
fi
