#!/usr/bin/env sh

# Guard against multiple/circular sourcing
if [ -z "$IS_STDINOR_SOURCED" ]; then
  IS_STDINOR_SOURCED=1
else
  echo "File 'stdin-or' already sourced, skipping..." >&2
  exit 0
fi

# NAME
#  stdin_or - Function to read from stdin or use arguments as fallback
#
# SYNOPSIS
#  stdin_or [...default_values]
#
# DESCRIPTION
#  Read from the standard input (stdin) and output it as is. 
#  However, if there is no input (i.e., if the script is run interactively or
#  not receiving input from a pipeline), it will instead return the first 
#  argument passed to the function.
#
# EXAMPLES
#  stdin_data=$(echo "input data" | stdin_or "default value")
#  # -> "input data"
#
#  stdin_data=$(stdin_or "default value")
#  # -> "default value"
#
#  stdin_data=$(stdin_or "default value" "one more value")
#  # -> "default value one more value"
stdin_or() {
  # If stdin is a terminal, return the arguments
  if [ -t 0 ]; then 
    printf "%s" "$1"
    return 0
  fi

  # Otherwise, read from stdin
  input=$(cat /dev/stdin)

  # If there is no input, also return the arguments
  if [ -z "$input" ]; then
    printf "%s" "$1"
  else
    printf "%s" "$input"
  fi
}

